=== acdean/acdepubdom/src/main/resources/acdepub.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">

  <xs:element name="book">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="info"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="prefix" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="part" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="chapter" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="act" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="appendix" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="info">
    <xs:complexType>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="author" maxOccurs="1"/>
          <xs:element ref="toctitle" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="title" maxOccurs="1"/>
          <xs:element ref="subtitle" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="date" maxOccurs="1"/>
          <xs:element ref="option" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="author" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="toctitle" type="xs:string"/>
  <xs:element name="subtitle" type="xs:string"/>
  <xs:element name="date" type="xs:integer"/>

  <xs:element name="option">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <!-- main paragraph class -->
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <!-- prefer em -->
        <xs:element ref="em" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="i" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="right" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="title" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="sc" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="smallcaps" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="p0" substitutionGroup="p"/>
  <xs:element name="p1" substitutionGroup="p"/>
  <xs:element name="p2" substitutionGroup="p"/>
  <xs:element name="p3" substitutionGroup="p"/>
  <xs:element name="footnote" substitutionGroup="p"/>

  <xs:element name="i" type="xs:string"/>
  <xs:element name="em" type="xs:string"/>
  <xs:element name="sc" type="xs:string"/>
  <xs:element name="smallcaps" type="xs:string"/>

  <xs:element name="right">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="sc" minOccurs="0"/>
        <xs:element ref="em" minOccurs="0"/>
        <xs:element ref="smallcaps" minOccurs="0"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="centre">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="sc" minOccurs="0"/>
        <xs:element ref="em" minOccurs="0"/>
        <xs:element ref="i" minOccurs="0"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="center" substitutionGroup="centre"/>

  <xs:element name="personae">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="person" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="person">
    <xs:complexType>
      <xs:attribute name="description" use="required"/>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- parts are full of chapters -->
  <!-- and can have title or info children and a title attribute -->
  <xs:element name="part">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="chapter" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="title"/>
    </xs:complexType>
  </xs:element>

  <!-- chapters mostly full of paragraphs -->
  <!-- and can have title or info children and a title attribute -->
  <xs:complexType name="chapterType">
    <xs:sequence>
      <xs:choice>
        <xs:element ref="title" minOccurs="0"/>
        <xs:element ref="info" minOccurs="0"/>
      </xs:choice>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="break" maxOccurs="unbounded"/>
        <xs:element ref="centre" maxOccurs="unbounded"/>
        <xs:element ref="hr" maxOccurs="unbounded"/>
        <xs:element ref="letter" maxOccurs="unbounded"/>
        <xs:element ref="p" maxOccurs="unbounded"/>
        <xs:element ref="poem" maxOccurs="unbounded"/>
        <xs:element ref="right" maxOccurs="unbounded"/>
        <xs:element ref="section" maxOccurs="unbounded"/>
        <xs:element ref="personae" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="title"/>
  </xs:complexType>
  <xs:element name="prefix" type="chapterType"/>
  <xs:element name="chapter" type="chapterType"/>
  <xs:element name="appendix" type="chapterType"/>

  <!-- acts are like chapters but for plays -->
  <xs:element name="act">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="direction"/>
          <xs:element ref="hr"/>
          <xs:element ref="speaker"/>
          <xs:element ref="speech"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="title"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="speaker" type="xs:string"/>
  <xs:element name="hr"/>

  <xs:element name="speech">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="direction"/>
        <xs:element ref="line"/>
        <xs:element ref="br"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="line" type="xs:integer"/>

  <xs:element name="br">
    <xs:complexType/>
  </xs:element>
  <xs:element name="break">
    <xs:complexType/>
  </xs:element>

  <xs:element name="section" type="xs:string"/>
  <xs:element name="direction" type="xs:string"/>

  <xs:element name="poem">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="poem1" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="poem2" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="poem3" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="poem4" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="poem5" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="poem1" type="xs:string"/>
  <xs:element name="poem2" type="xs:string"/>
  <xs:element name="poem3" type="xs:string"/>
  <xs:element name="poem4" type="xs:string"/>
  <xs:element name="poem5" type="xs:string"/>

  <!-- letters are wrappers like p -->
  <xs:element name="letter">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="p" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="right" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="break" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="centre" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== acdean/acdepubdom/src/test/resources/our_mutual_friend/our_mutual_friend_single.xml
<?xml version='1.0' encoding='UTF-8'?>
<book xmlns="http://www.koogy.clara.co.uk"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.koogy.clara.co.uk acdepub.xsd">

<info>
<author>Charles Dickens</author>
<toctitle>Our Mutual Friend (test)</toctitle>
<title>Our Mutual Friend (test)</title>
<date>1865</date>
<option name="part.title_text" value="Book The"/>
<option name="part.number_style" value="First"/>
<option name="chapter.title_text" value="Chapter"/>
<option name="chapter.number_style" value="I"/>
</info>

<part>
<title>The Cup And The Lip</title>
<chapter>
<title>On The Look Out</title>
<p>
In these times of ours, though concerning the exact year there is no need 
to be precise, a boat of dirty and disreputable appearance, with two 
figures in it, floated on the Thames, between Southwark bridge which is of 
iron, and London Bridge which is of stone, as an autumn evening was 
closing in. 
</p>
<p>
The figures in this boat were those of a strong man with ragged grizzled 
hair and a sun-browned face, and a dark girl of nineteen or twenty, 
sufficiently like him to be recognizable as his daughter. The girl rowed, 
pulling a pair of sculls very easily; the man, with the rudder-lines slack 
in his hands, and his hands loose in his waistband, kept an eager look 
out. He had no net, hook, or line, and he could not be a fisherman; his 
boat had no cushion for a sitter, no paint, no inscription, no appliance 
beyond a rusty boathook and a coil of rope, and he could not be a 
waterman; his boat was too crazy and too small to take in cargo for 
delivery, and he could not be a lighterman or river-carrier; there was no 
clue to what he looked for, but he looked for something, with a most 
intent and searching gaze. The tide, which had turned an hour before, was 
running down, and his eyes watched every little race and eddy in its broad 
sweep, as the boat made slight head-way against it, or drove stern 
foremost before it, according as he directed his daughter by a movement of 
his head. She watched his face as earnestly as he watched the river. But, 
in the intensity of her look there was a touch of dread or horror. 
</p>
<p>
Allied to the bottom of the river rather than the surface, by reason of 
the slime and ooze with which it was covered, and its sodden state, this 
boat and the two figures in it obviously were doing something that they 
often did, and were seeking what they often sought. Half savage as the man 
showed, with no covering on his matted head, with his brown arms bare to 
between the elbow and the shoulder, with the loose knot of a looser 
kerchief lying low on his bare breast in a wilderness of beard and 
whisker, with such dress as he wore seeming to be made out of the mud that 
begrimed his boat, still there was a business-like usage in his steady 
gaze. So with every lithe action of the girl, with every turn of her 
wrist, perhaps most of all with her look of dread or horror; they were 
things of usage. 
</p>
<p>
'Keep her out, Lizzie. Tide runs strong here. Keep her well afore the 
sweep of it.' 
</p>
<p>
Trusting to the girl's skill and making no use of the rudder, he eyed the 
coming tide with an absorbed attention. So the girl eyed him. But, it 
happened now, that a slant of light from the setting sun glanced into the 
bottom of the boat, and, touching a rotten stain there which bore some 
resemblance to the outline of a muffled human form, coloured it as though 
with diluted blood. This caught the girl's eye, and she shivered. 
</p>
<p>
'What ails you?' said the man, immediately aware of it, though so intent 
on the advancing waters; 'I see nothing afloat.' 
</p>
<p>
The red light was gone, the shudder was gone, and his gaze, which had come 
back to the boat for a moment, travelled away again. Wheresoever the 
strong tide met with an impediment, his gaze paused for an instant. At 
every mooring-chain and rope, at every stationery boat or barge that split 
the current into a broad-arrowhead, at the offsets from the piers of 
Southwark Bridge, at the paddles of the river steamboats as they beat the 
filthy water, at the floating logs of timber lashed together lying off 
certain wharves, his shining eyes darted a hungry look. After a darkening 
hour or so, suddenly the rudder-lines tightened in his hold, and he 
steered hard towards the Surrey shore. 
</p>
<p>
Always watching his face, the girl instantly answered to the action in her 
sculling; presently the boat swung round, quivered as from a sudden jerk, 
and the upper half of the man was stretched out over the stern. 
</p>
<p>
The girl pulled the hood of a cloak she wore, over her head and over her 
face, and, looking backward so that the front folds of this hood were 
turned down the river, kept the boat in that direction going before the 
tide. Until now, the boat had barely held her own, and had hovered about 
one spot; but now, the banks changed swiftly, and the deepening shadows 
and the kindling lights of London Bridge were passed, and the tiers of 
shipping lay on either hand. 
</p>
<p>
It was not until now that the upper half of the man came back into the 
boat. His arms were wet and dirty, and he washed them over the side. In 
his right hand he held something, and he washed that in the river too. It 
was money. He chinked it once, and he blew upon it once, and he spat upon 
it once,--'for luck,' he hoarsely said--before he put it in his 
pocket. 
</p>
<p>
'Lizzie!' 
</p>
<p>
The girl turned her face towards him with a start, and rowed in silence. 
Her face was very pale. He was a hook-nosed man, and with that and his 
bright eyes and his ruffled head, bore a certain likeness to a roused bird 
of prey. 
</p>
<p>
'Take that thing off your face.' 
</p>
<p>
She put it back. 
</p>
<p>
'Here! and give me hold of the sculls. I'll take the rest of the spell.' 
</p>
<p>
'No, no, father! No! I can't indeed. Father!--I cannot sit so near 
it!' 
</p>
<p>
He was moving towards her to change places, but her terrified 
expostulation stopped him and he resumed his seat. 
</p>
<p>
'What hurt can it do you?' 
</p>
<p>
'None, none. But I cannot bear it.' 
</p>
<p>
'It's my belief you hate the sight of the very river.' 
</p>
<p>
'I--I do not like it, father.' 
</p>
<p>
'As if it wasn't your living! As if it wasn't meat and drink to you!' 
</p>
<p>
At these latter words the girl shivered again, and for a moment paused in 
her rowing, seeming to turn deadly faint. It escaped his attention, for he 
was glancing over the stern at something the boat had in tow. 
</p>
<p>
'How can you be so thankless to your best friend, Lizzie? The very fire 
that warmed you when you were a babby, was picked out of the river 
alongside the coal barges. The very basket that you slept in, the tide 
washed ashore. The very rockers that I put it upon to make a cradle of it, 
I cut out of a piece of wood that drifted from some ship or another.' 
</p>
<p>
Lizzie took her right hand from the scull it held, and touched her lips 
with it, and for a moment held it out lovingly towards him: then, without 
speaking, she resumed her rowing, as another boat of similar appearance, 
though in rather better trim, came out from a dark place and dropped 
softly alongside. 
</p>
<p>
'In luck again, Gaffer?' said a man with a squinting leer, who sculled her 
and who was alone, 'I know'd you was in luck again, by your wake as you 
come down.' 
</p>
<p>
'Ah!' replied the other, drily. 'So you're out, are you?' 
</p>
<p>
'Yes, pardner.' 
</p>
<p>
There was now a tender yellow moonlight on the river, and the new comer, 
keeping half his boat's length astern of the other boat looked hard at its 
track. 
</p>
<p>
'I says to myself,' he went on, 'directly you hove in view, yonder's 
Gaffer, and in luck again, by George if he ain't! Scull it is, pardner--don't 
fret yourself--I didn't touch him.' This was in answer to a quick 
impatient movement on the part of Gaffer: the speaker at the same time 
unshipping his scull on that side, and laying his hand on the gunwale of 
Gaffer's boat and holding to it. 
</p>
<p>
'He's had touches enough not to want no more, as well as I make him out, 
Gaffer! Been a knocking about with a pretty many tides, ain't he pardner? 
Such is my out-of-luck ways, you see! He must have passed me when he went 
up last time, for I was on the lookout below bridge here. I a'most think 
you're like the wulturs, pardner, and scent 'em out.' 
</p>
<p>
He spoke in a dropped voice, and with more than one glance at Lizzie who 
had pulled on her hood again. Both men then looked with a weird unholy 
interest in the wake of Gaffer's boat. 
</p>
<p>
'Easy does it, betwixt us. Shall I take him aboard, pardner?' 
</p>
<p>
'No,' said the other. In so surly a tone that the man, after a blank 
stare, acknowledged it with the retort: 
</p>
<p>
'--Arn't been eating nothing as has disagreed with you, have you, 
pardner?' 
</p>
<p>
'Why, yes, I have,' said Gaffer. 'I have been swallowing too much of that 
word, Pardner. I am no pardner of yours.' 
</p>
<p>
'Since when was you no pardner of mine, Gaffer Hexam Esquire?' 
</p>
<p>
'Since you was accused of robbing a man. Accused of robbing a live man!' 
said Gaffer, with great indignation. 
</p>
<p>
'And what if I had been accused of robbing a dead man, Gaffer?' 
</p>
<p>
'You <i>couldn't</i> do it.' 
</p>
<p>
'Couldn't you, Gaffer?' 
</p>
<p>
'No. Has a dead man any use for money? Is it possible for a dead man to 
have money? What world does a dead man belong to? 'Tother world. What 
world does money belong to? This world. How can money be a corpse's? Can a 
corpse own it, want it, spend it, claim it, miss it? Don't try to go 
confounding the rights and wrongs of things in that way. But it's worthy 
of the sneaking spirit that robs a live man.' 
</p>
<p>
'I'll tell you what it is--.' 
</p>
<p>
'No you won't. I'll tell you what it is. You got off with a short time of
